# Generated by Django 5.2.1 on 2025-05-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('term_code', models.CharField(max_length=20, unique=True)),
                ('season', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-term_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=255)),
                ('schedule', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.term')),
            ],
            options={
                'unique_together': {('course', 'term', 'section')},
            },
        ),
    ]
