# Generated by Django 4.2.20 on 2025-05-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_examevent_importantdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code', 'course_code']},
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
