# Generated by Django 4.2.20 on 2025-05-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_old_course_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
    ]
