# Generated by Django 4.2.20 on 2025-05-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_date_fields_to_calendar_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['user', 'start_date', 'day_of_week', 'start_time']},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
