# Generated by Django 4.2.20 on 2025-06-15 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_add_date_fields_to_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='professor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('none', 'None')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
