# Generated by Django 4.2.20 on 2025-06-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_recurrence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('purple-gradient', 'Purple Dreams'), ('blue-gradient', 'Ocean Breeze'), ('green-gradient', 'Forest Fresh'), ('orange-gradient', 'Sunset Glow'), ('pink-gradient', 'Rose Petals'), ('teal-gradient', 'Tropical Waters'), ('yellow-gradient', 'Golden Hour'), ('indigo-gradient', 'Midnight Sky')], default='purple-gradient', max_length=20),
        ),
    ]
