# Generated by Django 4.2.20 on 2025-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_update_theme_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('sunset-vibes', 'Sunset Vibes'), ('ocean-depths', 'Ocean Depths'), ('tropical-paradise', 'Tropical Paradise'), ('fire-storm', 'Fire Storm'), ('cotton-candy', 'Cotton Candy'), ('cyber-neon', 'Cyber Neon'), ('golden-hour', 'Golden Hour'), ('royal-purple', 'Royal Purple'), ('forest-mist', 'Forest Mist'), ('berry-burst', 'Berry Burst'), ('electric-lime', 'Electric Lime'), ('cosmic-galaxy', 'Cosmic Galaxy'), ('twilight-sunset', 'Twilight Sunset')], default='sunset-vibes', max_length=30),
        ),
    ]
