# Generated by Django 4.2.20 on 2025-06-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_twilight_sunset_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('deep-violet-coral', 'Deep Violet Coral'), ('lavender-peach', 'Lavender Peach'), ('indigo-sunset', 'Indigo Sunset'), ('purple-pink-orange', 'Purple Pink Orange'), ('cotton-candy', 'Cotton Candy'), ('blue-purple-magenta', 'Blue Purple Magenta'), ('deep-plum-coral', 'Deep Plum Coral'), ('pink-orange-yellow', 'Pink Orange Yellow'), ('forest-mist', 'Forest Mist'), ('berry-burst', 'Berry Burst'), ('electric-lime', 'Electric Lime'), ('cosmic-galaxy', 'Cosmic Galaxy'), ('twilight-sunset', 'Twilight Sunset')], default='deep-violet-coral', max_length=30),
        ),
    ]
