# Generated by Django 4.2.20 on 2025-06-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_update_theme_choices_blue_red_gradients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('lavender-peach', 'Lavender Peach'), ('indigo-sunset', 'Indigo Sunset'), ('cotton-candy', 'Cotton Candy'), ('blue-purple-magenta', 'Blue Purple Magenta'), ('deep-plum-coral', 'Deep Plum Coral'), ('classic-black-white', 'Classic Black White'), ('midnight-ivory', 'Midnight Ivory'), ('cosmic-galaxy', 'Cosmic Galaxy'), ('twilight-sunset', 'Twilight Sunset'), ('midnight-light-blue', 'Midnight to Light Blue'), ('midnight-indigo-blue-cyan', 'Midnight to Indigo to Blue to Cyan'), ('deep-red-light-pink', 'Deep Red to Light Pink'), ('crimson-rose-white', 'Crimson to Rose White'), ('burgundy-blush', 'Burgundy to Blush'), ('dark-red-bright', 'Dark Red to Bright Red'), ('maroon-coral', 'Maroon to Coral'), ('wine-cherry', 'Wine Red to Cherry'), ('ruby-orange', 'Ruby Red to Orange'), ('scarlet-golden', 'Scarlet to Golden'), ('rose-peach', 'Rose Red to Peach'), ('deep-red-multi', 'Deep Red Multi-stop'), ('burgundy-cardinal-coral', 'Burgundy to Cardinal to Coral'), ('black-deep-bright', 'Black to Deep to Bright Red'), ('dark-burgundy-blood', 'Dark Burgundy to Blood Red'), ('midnight-red-fire', 'Midnight Red to Fire'), ('red-purple', 'Red to Purple'), ('cherry-magenta', 'Cherry to Magenta')], default='lavender-peach', max_length=40),
        ),
    ]
