# Generated by Django 4.2.20 on 2025-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_extra_blue_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('lavender-peach', 'Lavender Peach'), ('indigo-sunset', 'Indigo Sunset'), ('cotton-candy', 'Cotton Candy'), ('blue-purple-magenta', 'Blue Purple Magenta'), ('deep-plum-coral', 'Deep Plum Coral'), ('classic-black-white', 'Classic Black White'), ('midnight-ivory', 'Midnight Ivory'), ('cosmic-galaxy', 'Cosmic Galaxy'), ('twilight-sunset', 'Twilight Sunset'), ('midnight-light-blue', 'Midnight to Light Blue'), ('midnight-indigo-blue-cyan', 'Midnight to Indigo to Blue to Cyan'), ('black-deep-bright', 'Black to Deep to Bright Red')], default='lavender-peach', max_length=40),
        ),
    ]
