# Generated by Django 4.2.20 on 2025-06-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_user_calendar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sociallike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sociallike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='socialmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='SocialComment',
        ),
        migrations.DeleteModel(
            name='SocialLike',
        ),
        migrations.DeleteModel(
            name='SocialMessage',
        ),
        migrations.DeleteModel(
            name='SocialPost',
        ),
    ]
