# Generated by Django 4.2.20 on 2025-07-26 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_sync_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='My Schedule', max_length=200)),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='theme',
            field=models.CharField(choices=[('lavender-peach', 'Lavender Peach'), ('indigo-sunset', 'Indigo Sunset'), ('cotton-candy', 'Cotton Candy'), ('blue-purple-magenta', 'Blue Purple Magenta'), ('deep-plum-coral', 'Deep Plum Coral'), ('classic-black-white', 'Classic Black White'), ('midnight-ivory', 'Midnight Ivory'), ('cosmic-galaxy', 'Cosmic Galaxy'), ('twilight-sunset', 'Twilight Sunset'), ('midnight-light-blue', 'Midnight to Light Blue'), ('midnight-indigo-blue-cyan', 'Midnight to Indigo to Blue to Cyan'), ('black-deep-bright', 'Black to Deep to Bright Red'), ('green-blue', 'Green Blue'), ('warm-brown', 'Warm Brown'), ('lime-green', 'Lime Green'), ('mint-teal', 'Mint Teal'), ('blue-gradient', 'Blue Gradient')], default='blue-gradient', max_length=50),
        ),
        migrations.AddIndex(
            model_name='usercalendar',
            index=models.Index(fields=['user', 'day_of_week'], name='api_usercal_user_id_0c28ee_idx'),
        ),
        migrations.AddIndex(
            model_name='usercalendar',
            index=models.Index(fields=['user', 'start_date'], name='api_usercal_user_id_27a0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='usercalendar',
            index=models.Index(fields=['created_at'], name='api_usercal_created_c7f24e_idx'),
        ),
        migrations.AddField(
            model_name='sharedschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sharedschedule',
            index=models.Index(fields=['user', 'created_at'], name='api_shareds_user_id_b1393d_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedschedule',
            index=models.Index(fields=['created_at'], name='api_shareds_created_863426_idx'),
        ),
    ]
