# Generated by Django 4.2.23 on 2025-08-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_sharedschedule_alter_course_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('lavender-peach', 'Lavender Peach'), ('indigo-sunset', 'Indigo Sunset'), ('cotton-candy', 'Cotton Candy'), ('blue-purple-magenta', 'Blue Purple Magenta'), ('deep-plum-coral', 'Deep Plum Coral'), ('classic-black-white', 'Classic Black White'), ('midnight-ivory', 'Midnight Ivory'), ('cosmic-galaxy', 'Cosmic Galaxy'), ('twilight-sunset', 'Twilight Sunset'), ('midnight-light-blue', 'Midnight to Light Blue'), ('midnight-indigo-blue-cyan', 'Midnight to Indigo to Blue to Cyan'), ('black-deep-bright', 'Black to Deep to Bright Red'), ('green-blue', 'Green Blue'), ('warm-brown', 'Warm Brown'), ('lime-green', 'Lime Green'), ('mint-teal', 'Mint Teal'), ('peach-mint', 'Peach Mint'), ('sky-lavender', 'Sky Lavender'), ('sunset-gold', 'Sunset Gold'), ('forest-moss', 'Forest Moss')], default='lavender-peach', max_length=40),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='theme',
            field=models.CharField(choices=[('lavender-peach', 'Lavender Peach'), ('indigo-sunset', 'Indigo Sunset'), ('cotton-candy', 'Cotton Candy'), ('blue-purple-magenta', 'Blue Purple Magenta'), ('deep-plum-coral', 'Deep Plum Coral'), ('classic-black-white', 'Classic Black White'), ('midnight-ivory', 'Midnight Ivory'), ('cosmic-galaxy', 'Cosmic Galaxy'), ('twilight-sunset', 'Twilight Sunset'), ('midnight-light-blue', 'Midnight to Light Blue'), ('midnight-indigo-blue-cyan', 'Midnight to Indigo to Blue to Cyan'), ('black-deep-bright', 'Black to Deep to Bright Red'), ('green-blue', 'Green Blue'), ('warm-brown', 'Warm Brown'), ('lime-green', 'Lime Green'), ('mint-teal', 'Mint Teal'), ('blue-gradient', 'Blue Gradient'), ('peach-mint', 'Peach Mint'), ('sky-lavender', 'Sky Lavender'), ('sunset-gold', 'Sunset Gold'), ('forest-moss', 'Forest Moss')], default='blue-gradient', max_length=50),
        ),
    ]
