# Generated by Django 4.2.23 on 2025-09-25 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0031_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=50)),
                ('term_display', models.CharField(max_length=100)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('generation_context', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_version', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=255)),
                ('section_code', models.CharField(max_length=20)),
                ('component', models.CharField(max_length=10)),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructor', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('class_number', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.schedule')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['schedule', 'course_code'], name='api_schedul_schedul_afda2e_idx'), models.Index(fields=['schedule', 'day_of_week', 'start_time'], name='api_schedul_schedul_bf4db4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_request', models.TextField()),
                ('adjustment_type', models.CharField(max_length=50)),
                ('affected_courses', models.JSONField(default=list)),
                ('previous_state', models.JSONField(default=dict)),
                ('new_state', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='api.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['schedule', 'created_at'], name='api_schedul_schedul_9232b8_idx'), models.Index(fields=['adjustment_type'], name='api_schedul_adjustm_105b8a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user', 'term', 'is_active'], name='api_schedul_user_id_314b69_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user', 'created_at'], name='api_schedul_user_id_c30663_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['dataset_version'], name='api_schedul_dataset_4fe61d_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'term'), name='unique_active_schedule_per_user_term'),
        ),
    ]
