# Generated by Django 4.2.24 on 2025-10-23 04:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0032_schedule_scheduleentry_scheduleadjustment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIResponseFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Generation"),
                            ("chat", "Chat Response"),
                            ("schedule", "Schedule Generation"),
                            ("other", "Other AI Response"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                (
                    "user_input",
                    models.TextField(help_text="The original user message/prompt"),
                ),
                (
                    "ai_response",
                    models.TextField(help_text="The AI-generated response"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        help_text="1=Very Poor, 5=Excellent",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed feedback from user",
                        null=True,
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(
                        default=True, help_text="Was this response helpful?"
                    ),
                ),
                (
                    "is_accurate",
                    models.BooleanField(
                        default=True, help_text="Was this response accurate?"
                    ),
                ),
                (
                    "is_professional",
                    models.BooleanField(
                        default=True,
                        help_text="Was this response professional? (for emails)",
                    ),
                ),
                (
                    "is_relevant",
                    models.BooleanField(
                        default=True,
                        help_text="Was this response relevant to the request?",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-4o-mini", help_text="AI model used", max_length=50
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        default="v1.0",
                        help_text="Version of prompt used",
                        max_length=20,
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        blank=True, help_text="Chat session ID if applicable", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_response_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_responses", models.IntegerField(default=0)),
                ("total_feedback_received", models.IntegerField(default=0)),
                (
                    "feedback_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of responses that received feedback",
                    ),
                ),
                ("average_rating", models.FloatField(default=0.0)),
                ("positive_feedback_count", models.IntegerField(default=0)),
                ("negative_feedback_count", models.IntegerField(default=0)),
                ("email_feedback_count", models.IntegerField(default=0)),
                ("chat_feedback_count", models.IntegerField(default=0)),
                ("average_email_rating", models.FloatField(default=0.0)),
                (
                    "email_modification_rate",
                    models.FloatField(
                        default=0.0, help_text="% of emails modified by users"
                    ),
                ),
                ("top_issue_1", models.CharField(blank=True, max_length=50, null=True)),
                ("top_issue_2", models.CharField(blank=True, max_length=50, null=True)),
                ("top_issue_3", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "feedback_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EmailFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_subject",
                    models.CharField(
                        help_text="AI-generated subject line", max_length=200
                    ),
                ),
                (
                    "generated_body",
                    models.TextField(help_text="AI-generated email body"),
                ),
                (
                    "professor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "professor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "subject_quality",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        help_text="Quality of generated subject line",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "body_quality",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        help_text="Quality of generated email body",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("too_formal", models.BooleanField(default=False)),
                ("too_casual", models.BooleanField(default=False)),
                ("wrong_tone", models.BooleanField(default=False)),
                ("missing_context", models.BooleanField(default=False)),
                ("grammatical_errors", models.BooleanField(default=False)),
                ("user_modified_subject", models.BooleanField(default=False)),
                ("user_modified_body", models.BooleanField(default=False)),
                (
                    "final_subject_sent",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("final_body_sent", models.TextField(blank=True, null=True)),
                (
                    "ai_feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_details",
                        to="api.airesponsefeedback",
                    ),
                ),
            ],
            options={
                "db_table": "email_feedback",
            },
        ),
        migrations.AddIndex(
            model_name="airesponsefeedback",
            index=models.Index(
                fields=["feedback_type", "rating"],
                name="ai_response_feedbac_0bea78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="airesponsefeedback",
            index=models.Index(
                fields=["created_at"], name="ai_response_created_26f481_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponsefeedback",
            index=models.Index(
                fields=["user", "feedback_type"], name="ai_response_user_id_a1eff9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airesponsefeedback",
            index=models.Index(
                fields=["is_helpful", "rating"], name="ai_response_is_help_5272a8_idx"
            ),
        ),
    ]
