# Generated by Django 4.2.24 on 2025-10-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_add_feedback_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="term",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
