# Generated by Django 4.2.23 on 2026-02-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_term_to_calendar_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('purple', 'Purple'), ('pink', 'Pink'), ('orange', 'Orange'), ('amber', 'Amber'), ('teal', 'Teal'), ('violet', 'Violet'), ('slate', 'Slate')], default='purple', max_length=40),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('purple', 'Purple'), ('pink', 'Pink'), ('orange', 'Orange'), ('amber', 'Amber'), ('teal', 'Teal'), ('violet', 'Violet'), ('slate', 'Slate')], default='purple', max_length=50),
        ),
    ]
