# Generated by Django 4.2.23 on 2026-02-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_update_theme_choices_simplified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='theme',
            field=models.CharField(blank=True, default='purple', max_length=40),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='theme',
            field=models.CharField(blank=True, default='purple', max_length=50),
        ),
    ]
